### ISSUE TITLE
Bug when row starts with 4 spaces

### ISSUE THREAD

**Issue by Lucas-C** [RedBug312/markdown-it-multimd-table#1]
Hello.

First off, thank you very much for writing this plugin !

I think I may have found a little bug.

When I run the example in the README, I obtain the following:
```html
<table>
<thead>
<tr>
<th></th>
<th style="text-align:center" colspan="2">Grouping</th>
</tr>
<tr>
<th>First Header</th>
<th style="text-align:center">Second Header</th>
<th style="text-align:right">Third Header</th>
</tr>
</thead>
<tbody>
<tr>
<td>Content</td>
<td style="text-align:center" colspan="2"><em>Long Cell</em></td>
</tr>
<tr>
<td>Content</td>
<td style="text-align:center"><strong>Cell</strong></td>
<td style="text-align:right">Cell</td>
</tr>
</tbody>
</table>
<p>New section   |     More      |         Data |
And more      | With an escaped '|'        ||
[Prototype table]</p>
```

It looks like when a row starts with 4 spaces, the table stops and gets converted into a `<pre><code>` block.
There is a minimal test demonstrating this:
```html
A | B
--|--
0 |1

A    | B
-----|--
    0|1
```

Do you think this could be fixed ?

**Comment by redbug312** [comment]
Hi, thanks for your issue! 😃
I've commited some changes to a new branch `indent-row` to solve this bug. 
Changes can be seen in PR #3.

Now the table will be viewed as code only if the separator line have indentations. For example,
```
    A| B
-----|--
    0| 1
```
would be viewed as a table, while
```
    A| B
    -|--
    0| 1
```
is not.

I will merge the branch into master and publish to npm as version `3.0.0` in 3 days.
Thanks for posing the bug again!

**Comment by Lucas-C** [comment]
Thank you very much for the very quick fix !
