### ISSUE TITLE
Browser loader is in conflict with deflist extention

### ISSUE THREAD

**Issue by jf0772256** [RedBug312/markdown-it-multimd-table#10]
I hate to point this out but the markdownitDefList in your code and the extention for <dl></dl> are the same thus causing conflicts when they are loaded into the launcher in the same instance.

**Comment by redbug312** [comment]
Hi, could you describe more about the cases where the confliction is triggered?

I've only tried the combined example as below
```markdown
|             |          Grouping           || 
First Header  | Second Header | Third Header | 
 ------------ | :-----------: | -----------: | 
Content       |          *Long Cell*        || 
Content       |   **Cell**    |         Cell | 
                                               
New section   |     More      |         Data | 
And more      | With an escaped '\|'         ||
[Prototype table]                              

Term 1

:   Definition 1
with lazy continuation.

Term 2 with *inline markup*

:   Definition 2

        { some code, part of Definition 2 }

    Third paragraph of definition 2.

_Compact style:_

Term 1
  ~ Definition 1

Term 2
  ~ Definition 2a
  ~ Definition 2b
```
And it looks fine.

![issue](https://user-images.githubusercontent.com/11537681/38936085-9ad822c2-4352-11e8-8213-819af6331739.png)

**Comment by jf0772256** [comment]
`(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.markdownitDeflist = f()}})(function(){var define,module,exports;return (function(){function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s}return e})()({1:[function(require,module,exports){`

is the same line as the defList extention, it works, but it may cause confusion, I changed the `else{g=this}g.markdownitDeflist = f()}})(f`
to `else{g=this}g.markdownitMultiLineTbl = f()}})(f`

**Comment by redbug312** [comment]
Thanks! I should be more careful when copying and pasting. 😔 
Would you mind creating a pull request to patch it?

**Comment by jf0772256** [comment]
I did pull request is waiting review and approval
