### ISSUE TITLE
How only merge one column?

### ISSUE THREAD

**Issue by LinFeng1997** [RedBug312/markdown-it-multimd-table#15]
For example:
<table>
    <thead>
    <tr>
        <th>one</th> 
        <th>two</th> 
   </tr>
   </thead>
    <tr>
        <td rowspan="2">merge columns</td>    
        <td >1-2</td>  
    </tr>
    <tr>
        <td >2-2</td>  
    </tr>
</table>

Thank you~

**Comment by redbug312** [comment]
This plugin haven't implement `rowspan` attribute yet, since it wasn't defined in MultiMarkdown.

If there's another table syntax that is compatible and easy to implement, I would adopt it as an optional feature. :sweat_smile:

**Comment by Menci** [comment]
I'm working on way to another merge cells: just merge adjacent cells with same content.

See https://github.com/Menci/markdown-it-merge-cells.

**Comment by pmccloghrylaing** [comment]
A rowspan option would be really useful. I can see 3 types of approaches:

1. @Menci's approach of merging identical cells. I'm not sure whether it makes sense to use it only for rowspan, or whether it should be enabled for colspan as well? With long cell content this could mean a lot of duplication, e.g.

   ```
   | Heading    ||| // colspan
   |----|----|----|
   | A  | B  | C  | // rowspan
   | A  | D  | E  |
   | F      || G  | // rowspan & colspan
   | F      || H  |
   ```

2. Merging with empty cells. Would need to differentiate from the colspan feature, although it could be detected based on presence of spaces - `||` indicates merge horizontally while `| |` indicates merge vertically, e.g.

   ```
   | Heading    ||| // colspan
   |----|----|----|
   | A  | B  | C  | // rowspan
   |    | D  | E  |
   | F      || G  | // rowspan & colspan
   |        || H  |
   ```

3. The other option is to use a special token to indicate merge up. I've come across `^` being  used (shd101wyy/markdown-preview-enhanced#479) and had also considered `"` as a [ditto mark](https://en.wikipedia.org/wiki/Ditto_mark) or maybe `^^`, e.g.

   ```
   | Heading    ||| // colspan
   |----|----|----|
   | A  | B  | C  | // rowspan
   | ^^ | D  | E  |
   | F      || G  | // rowspan & colspan
   | ^^     || H  |
   ```

My preference is for something like `^^` - @RedBug312 I'm happy to contribute a PR for it, just let me know which approach fits best.

**Comment by redbug312** [comment]
Thanks in advance @pmccloghrylaing. Third solution with ditto marks seems more intuitional than other two solutions to me. Because it's out of multimarkdown spec, I'd like this to be implemented as an optional feature named `enableRowspan`.

**Comment by Menci** [comment]
@pmccloghrylaing My implementation merges both row and column. I think the advantage is that a normal renderer without merge cells implementation will give a readable result.
