### ISSUE TITLE
Can't create tables without headers

### ISSUE THREAD

**Issue by prindacerk** [RedBug312/markdown-it-multimd-table#21]
There's an issue if I try to create a table without a header row defined. It won't recognize the markdown as table at all. I have to create an empty header row for it to work.

Would be better if we can have a surrounding markdown syntax that can identify the table therefore eliminate the need for a table header row.

**Comment by redbug312** [comment]
Thanks, I will add this feature into `develop` branch, which is going to released as version 4.0.0. Headerless table seems to against MultiMarkdown [requirement 2](https://fletcher.github.io/MultiMarkdown-6/syntax/tables.html), so this will be added as an optional feature only.

Also, a fenced (surrounding?) table syntax is far incompatable with many markdown table syntax, so I would have the headerless table looks like this:
```
|----------|-----|
|Headerless|table|
```

**Comment by redbug312** [comment]
Hi, this feature has just been implemented in `develop` branch. You can switch to this branch before this branch is released.
