### ISSUE TITLE
Vscode auto format more | when using Multiline

### ISSUE THREAD

**Issue by nhattran998** [RedBug312/markdown-it-multimd-table#23]
@RedBug312 , here this format after Vscode automatically formatted:

``` markdown
|     A1      | A2  | B1  | B2  |           C1            | C2  |
| :---------: | :-: | :-: | :-: | :---------------------: | :-: |
| appropriate |  a  |  a  |  a  |   - appropriately adv   |     | \ |
|             |     |     |     | - inappropriate neg adj |     |
```

And this is the result:
![image](https://user-images.githubusercontent.com/24296018/71433452-ca4a0f80-2711-11ea-98bb-ea4805934392.png)

But how can use it like your README.md but do not disable VSCode's formatOnSave for markdown file? (Sorry, I'm a newbie)

**Comment by redbug312** [comment]
Thanks for the report. This plugin can't do anything to modification by editors/IDEs, since semantic meanings have changed after auto-formatting.
A better solution is to configure VSCode formatter; to avoid trailing `\` from recognizing as another table cell. Can you provide the code before formatting, and the formatter you're using?

**Comment by nhattran998** [comment]
> Thanks for the report. This plugin can't do anything to modification by editors/IDEs, since semantic meanings have changed after auto-formatting.
> A better solution is to configure VSCode formatter; to avoid trailing `\` from recognizing as another table cell. Can you provide the code before formatting, and the formatter you're using?

Sorry for the reply too late 😅. I'm just using this config:
```json
// Config markdown
  "[markdown]": {
    "editor.fontFamily": "Menlo, Monaco, 'Courier New', monospace",
    "editor.formatOnSave": true
  },
``` 
And installed plugins: `Prettier` and `Markdown Shortcuts` of `mdickin`

**Comment by redbug312** [comment]
Prettier does the markdown auto-formatting. But there's no option for this feature, and I guess they won't add the option in the future.

First,  trailing `\` is out of most Markdown specs (CommonMark and GFM that prettier adopts; even MultiMarkdown itself). Also, from [the docs](https://prettier.io/docs/en/option-philosophy.html), no extensions supported; and few options are carefully chosen. It seems no reason for them to break their principle to include an uncommon feature.

Either you can turn to another more expressive formatter, or you can use [the workaround](https://prettier.io/docs/en/ignore.html#markdown) that flags the **whole paragraph (table)** to be ignored:
```markdown
<!-- prettier-ignore -->
|     A1      | A2  | B1  | B2  |           C1            | C2  |
| :---------: | :-: | :-: | :-: | :---------------------: | :-: |
| appropriate |  a  |  a  |  a  |   - appropriately adv   |     | \
|             |     |     |     | - inappropriate neg adj |     |
```

You can see the playground result [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfABJzBBAjFrDbAJkwwCF90LTqD7MBhKhgjR21AHSgyQFpBQoUjoDRffhPTixw+QoXTZ3XugCGAB00AnCLoCW6+HQ1lM682dPp+G7XsPG4AGwCeGgCYA3QvQxcgWqs-qFsoXYGUFq6+jpGJlBwAOZeAFY2ZDw8ADwAhILounAwMAZwOvwGyVAQOnC2-AB8PBgEeAxEnOiU5uTdIUwsg+ycrTKKgspSctPTkwsis9TjMY7xzqaWW1bbbbb2sU7w7l6+Vn6B44N+4Xd+kdEOcQkNSanqnhn7ZCAANCB9GVoABnZCgdQ6PQAdwACpCEGCUOpvBADJ5-iAAEY6dRgADWJQAypo8VFksgYDoAK5wAEACxgAFsXAB1ekGeAg0lgOBExGcgzeTluZDgEFggFREEVGCw3HJJnqZAAM3ULhlALSIIAHuRcQTieomXAADJROCq9WakDanVE8kuOAARWpEHgVo1dJApJ0Mp0YqVOnxngg0KgmMMsFZ6Jg9OQAA4AAwA2Iy1m4zRi4r+7yWgEARzd8Hl+iRIHUIP4STgnlrmPqRYM9Xl6kVyqQaq9AJlTIMlJp3pBjpdxctnet3pg6ixMc8ceQxABVPUBhc5MYECZSrFtSSmOpMoAKjOkV2bd5aQBJKB12BEsDxTQwbC3okwNxOz0ygC+P6AA).

**Comment by nhattran998** [comment]
@RedBug312 Thanks bro, it's worked! Yeah, and happy new year 🥳!
