### ISSUE TITLE
Feature request: syntax to define thick borders both per column / row and per cell

### ISSUE THREAD

**Issue by Meteor0id** [RedBug312/markdown-it-multimd-table#28]
Lets say we want to make a Sudoku. It would help to have tick lines, to separate each block of 9 cells. We would need syntax to define thicker lines. Just defining this one in the header and first column would suffice, no need to define a thick border on every cell.

Or lets say we want to recreate the periodic table and you want to have a zigzag line to separate metals from non-metals. The thick line should be defined per cell, and there should be several options:
normal cell, thick border on left, thick border on right, tick on top, bottom, left and top, left and bottom, top and bottom, right and bottom, right and top, top left and bottom, ... anyway you get it.

We're not trying to reinvent CSS, but this sort of styling really helps bring different kinds of table content which are currently not possible.

**Comment by redbug312** [comment]
Reason explained in issue #26 :disappointed_relieved:. Thanks for this nice idea still.
