### ISSUE TITLE
provide example syntax for avoiding empty cells from colapsing into longcells

### ISSUE THREAD

**Issue by Meteor0id** [RedBug312/markdown-it-multimd-table#29]
What I am missing in the examples provided is how to differentiate between long cells and cells which border an empty cell. How to use this syntax in such way that my empty cells won't collapse into long cells?

**Comment by redbug312** [comment]
In MultiMarkdown, cells with spaces only will be converted to empty cells (spaces are trimmed). Below is the example:

```
|Header A|        |Header B|
|--------|--------|--------|
|Content         ||        |
```

<table>
<thead>
<tr>
<th>Header A</th>
<th></th>
<th>Header B</th>
</tr>
</thead>
<tbody>
<tr>
<td colspan="2">Content</td>
<td></td>
</tr>
</tbody>
</table>
