### ISSUE TITLE
update markdown-it dependency

### ISSUE THREAD

**Issue by commenthol** [RedBug312/markdown-it-multimd-table#31]
Currently this package is using an outdated and vulnerable version of markdown-it.

See https://snyk.io/test/npm/markdown-it-multimd-table

Can you please bump the dependencies to markdown-it@^11 ?

**Comment by redbug312** [comment]
Sorry for late reply.
Dependency got updated to `markdown-it^11.0.0`. Thanks for the report!

**Comment by commenthol** [comment]
@RedBug312 Thanks for updating. Could you please publish the updated version on npm?

**Comment by redbug312** [comment]
Sure. Just published as version 4.0.3. :smiley:
