### ISSUE TITLE
option to customize caption syntax

### ISSUE THREAD

**Issue by changethe** [RedBug312/markdown-it-multimd-table#50]
The current caption syntax `[caption]` doesn't allow links inside the caption.
It would be nice to have an option to define a different marker for the caption.

Additionally it would be nice to have an option to disable the generation of the caption id (it can get kinda long if the caption is a bit longer).

[markdown-it-attribution](https://github.com/dweidner/markdown-it-attribution) does this really well.

**Comment by redbug312** [comment]
I just found the problem to caption links and will fix it in next version.
Also, an option `autolabel: false` will be available to disable id auto-generation.

**Comment by redbug312** [comment]
Closed for version 4.2.0.

**Comment by changethe** [comment]
you made a typo in the documentation:  under usage the example setting for turning off the autolabel says `aotolabel:  true` should be `autolabel`.

thanks a lot for fixing this btw!
