### ISSUE TITLE
muilti line table,why only right line can be consider as markdown,but not all?

### ISSUE THREAD

**Issue by huanling-SDS** [RedBug312/markdown-it-multimd-table#55]
Your project is so awesome , I like it and I always use it at my obsidian , thanks for your job.
I have a little question these day, like this:
![image](https://user-images.githubusercontent.com/30822241/215399032-742dd1d1-6fa3-460d-a751-0da20191d842.png)

the right-column can show the right markdown style view
but the-left-column can’t.

I'd want to know, is there a way to show them the same ? all markdown style.

and why do design like this.

Thank you very much.

**Comment by redbug312** [comment]
Glad that you're enjoying this plugin!

For simplicity, the multiline backslash also enables block-level rendering for lists, quotes, code blocks, etc. The whole table cell is sent to markdown-it itself for block-level rendering. There, the 4-space indentation triggers markdown-it for code blocks.

Stripping the indentation from the left column will show the same result.
